# -*- coding: utf-8 -*-
"""mini project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zaE8SmeUezMZX8ww0lXCycJnwU1_n95

# task 2
taking JSON file -> clean it -> save as CSV

at first i actually tired to open a non-notebook file as a notbook
then i created a new notebook and uploaded json by one code then it was loaded
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_json("trends_20260408.json")

import os
print(os.listdir())

"""this actually shows the exact file name"""

df.head()

"""we will see first 5 rows"""

df.info()

"""this tells how many rows, columns, missing values."""

df.isnull().sum()

"""shows how many empty values in each column"""

sf = df.dropna(subset=["title"])

"""this removes rows with no title"""

df["score"] = df["score"].fillna(0)
df["num_comments"] = df["num_comments"].fillna(0)

"""fill missing numbers"""

df = df.drop_duplicates(subset=["post_id"])

"""remmoves duplicates"""

df.to_csv("cleaned_trends.csv", index=False)

"""saved as a clean CSV"""

from google.colab import files
files.download("cleaned_trends.csv")

"""downloaded and final output as cleaned_trends.csv

# Task 3
data analysis
"""

import pandas as pd

df = pd.read_csv("cleaned_trends.csv")

"""loading my CSV"""

df.head()

"""previewing again"""

df["category"].value_counts()

"""count stories per category"""

df["score"].mean()

"""average score"""

df["num_comments"].mean()

"""average comments"""

df.sort_values(by= "score", ascending=False).head(5)

"""top 5 highest scored posts"""

df["author"].value_counts().head(5)

"""most active authors"""

df.groupby("category")["score"].mean()

"""# Task 4"""

import pandas as pd

df = pd.read_csv("cleaned_trends.csv")

import matplotlib.pyplot as plt

df["category"].value_counts().plot(kind="bar")

plt.title("Number of Stories per Category")
plt.xlabel("Category")
plt.ylabel("Count")

plt.show()

top_scores = df.sort_values(by="score", ascending=False).head(10)

top_scores.plot(x="title", y="score", kind="bar")

plt.title("Top 10 Highest Scored Stories")
plt.xlabel("Story Title")
plt.ylabel("Score")

plt.xticks(rotation=45)

plt.show()

df["num_comments"].plot(kind="hist")

plt.title("Distribution of Comments")
plt.xlabel("Number of Comments")

plt.show()

plt.savefig("graph.png")

