# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJM37j1BsZu7bRSZA0ZPJn9ZFkOQZGGs
"""

import requests

"""this lets python talk to internet"""

url = "https://hacker-news.firebaseio.com/v0/topstories.json"

"""this is where data lives"""

headers = {"User-Agent": "TrendPulse/1.0"}

"""this like verifying you are a human"""

response = requests.get(url, headers=headers)

"""we ask for data in this"""

if response.status_code == 200:
  data = response.json()
  print(len(data))
else:
    print("Failed to fetch data")

"""now we need to open one and see inside"""

first_id = data[0]
print(first_id)

item_url = f"https://hacker-news.firebaseio.com/v0/item/{first_id}.json"
print(item_url)

"""#why f string?
we are inserting the ID dynamically
"""

res = requests.get(item_url, headers=headers)

if res.status_code == 200:
    story = res.json()
    print(story)
else:
    print("Failed to fetch story")

def get_category(title):
    title = title.lower()

    if "ai" in title or "tech" in title:
        return "technology"

    return None

print(get_category("New AI tool released"))

"""right now the code recognises technology but the assignment need 5 categories"""

def get_category(title):
    title = title.lower()

    if any(word in title for word in ["ai","software","tech","code","computer","data","cloud","api","gpu","llm","startup","app","programming"]):
        return "technology"

    elif any(word in title for word in ["war","government","country","president","election","climate","attack","global","policy","economy","minister"]):
        return "worldnews"

    elif any(word in title for word in ["nfl","nba","fifa","sport","game","team","player","league","match","tournament","championship"]):
        return "sports"

    elif any(word in title for word in ["research","study","space","physics","biology","discovery","nasa","genome","science","experiment"]):
        return "science"

    elif any(word in title for word in ["movie","film","music","netflix","game","book","show","award","streaming","series","tv"]):
        return "entertainment"

    return None

print(get_category("AI is changing the world"))
print(get_category("NASA research a new planet"))
print(get_category("New movie released on Netflix"))

import requests

url = "https://hacker-news.firebaseio.com/v0/topstories.json"
headers = {"User-Agent": "TrendPulse/1.0"}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    story_ids = data[:2000]
    print("IDs loaded:", len(story_ids))
else:
    print("Failed")

collected_data = []

from datetime import datetime
import time

collected_data = []

for story_id in story_ids:
    try:
        # Stop when we reach exactly 100
        if len(collected_data) == 100:
            break

        item_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"
        res = requests.get(item_url, headers=headers)

        if res.status_code != 200:
            continue

        story = res.json()

        if not story or "title" not in story:
            continue

        category = get_category(story["title"])

        # If no category, skip (keeps it clean)
        if not category:
            continue

        data_item = {
            "post_id": story.get("id"),
            "title": story.get("title"),
            "category": category,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        collected_data.append(data_item)

        time.sleep(0.1)

    except:
        continue

print(len(collected_data))

import json
import os
from datetime import datetime

if not os.path.exists("data"):
    os.makedirs("data")

filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w") as f:
     json.dump(collected_data, f, indent=4)

print(f"Collected {len(collected_data)} stories. Saved to {filename}")

from google.colab import files
files.download(filename)